import type { Category, Company, Listing, UserRole } from "@/types";
import { getSupabaseAnonKey, getSupabaseUrl } from "@/lib/supabase/env";

export function isDemoMode() {
  const url = getSupabaseUrl();
  const key = getSupabaseAnonKey();
  return (
    process.env.DEMO_MODE === "true" ||
    process.env.NEXT_PUBLIC_DEMO_MODE === "true" ||
    url.includes("placeholder") ||
    key.includes("placeholder")
  );
}

export const DEMO_SESSION_COOKIE = "b2b_demo_session";

export interface DemoUser {
  id: string;
  email: string;
  password: string;
  full_name: string;
  role: UserRole;
  company: Company;
}

export const DEMO_DEMAND_USER = {
  id: "demo-demand-001",
  email: "demo@talep.com",
  password: "Talep2026!",
} as const;

export const DEMO_PRODUCER_USER = {
  id: "demo-producer-001",
  email: "demo@uretici.com",
  password: "Uretici2026!",
} as const;

export const DEMO_PRODUCER_FREE_USER = {
  id: "demo-supplier-free-001",
  email: "demo@tedarikci.com",
  password: "Tedarikci2026!",
} as const;

export const DEMO_ADMIN_USER = {
  id: "demo-admin-001",
  email: "demo@admin.com",
  password: "Admin2026!",
} as const;

export const DEMO_USERS: DemoUser[] = [
  {
    id: DEMO_DEMAND_USER.id,
    email: DEMO_DEMAND_USER.email,
    password: DEMO_DEMAND_USER.password,
    full_name: "Ahmet Yılmaz",
    role: "demand_owner",
    company: {
      id: "demo-company-001",
      owner_id: "demo-demand-001",
      name: "Demo Kurumsal A.Ş.",
      type: "demand_owner",
      status: "approved",
      description:
        "İstanbul merkezli kurumsal firma. Metal, plastik ve tekstil alanlarında üretim tedariki yönetiyoruz. 15 yıllık tedarik deneyimimizle güvenilir iş ortaklıkları kuruyoruz.",
      logo_url: null,
      website: "https://demo-kurumsal.com",
      tax_number: "1234567890",
      address: "Maslak, İstanbul",
      city: "İstanbul",
      phone: "+90 212 000 00 00",
      email: "demo@talep.com",
      verified: true,
      slug: "demo-kurumsal",
      tagline: "Güvenilir tedarik yönetimi",
      cover_image_url: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&h=400&fit=crop",
      founded_year: 2010,
      employee_count: "100-250",
      profile_public: true,
      membership_plan: "free",
      created_at: new Date().toISOString(),
    },
  },
  {
    id: DEMO_PRODUCER_FREE_USER.id,
    email: DEMO_PRODUCER_FREE_USER.email,
    password: DEMO_PRODUCER_FREE_USER.password,
    full_name: "Ayşe Demir",
    role: "producer",
    company: {
      id: "demo-supplier-free-co",
      owner_id: DEMO_PRODUCER_FREE_USER.id,
      name: "Ege Tekstil Tedarik",
      type: "producer",
      status: "approved",
      description:
        "Tekstil ve konfeksiyon tedarikinde B2B çözümler sunuyoruz. Ücretsiz planda aylık 10 ilana teklif verebilir, Pro ile sınırsız erişim ve profil sayfası açabilirsiniz.",
      category_ids: ["sub-textile-knit", "sub-textile-dye"],
      logo_url: null,
      website: "https://ege-tekstil-tedarik.com",
      tax_number: "1122334455",
      address: "Organize Sanayi Bölgesi, Denizli",
      city: "Denizli",
      phone: "+90 258 000 00 00",
      email: DEMO_PRODUCER_FREE_USER.email,
      verified: false,
      slug: "ege-tekstil-tedarik",
      tagline: "Tekstil tedarik ortağınız",
      cover_image_url: null,
      founded_year: 2018,
      employee_count: "10-50",
      profile_public: false,
      membership_plan: "free",
      created_at: new Date().toISOString(),
    },
  },
  {
    id: DEMO_PRODUCER_USER.id,
    email: DEMO_PRODUCER_USER.email,
    password: DEMO_PRODUCER_USER.password,
    full_name: "Mehmet Kaya",
    role: "producer",
    company: {
      id: "producer-003",
      owner_id: "demo-producer-001",
      name: "Marmara Metal San.",
      type: "producer",
      status: "approved",
      description:
        "Paslanmaz çelik ve metal işleme alanında 20 yıllık deneyim. ISO 9001 sertifikalı tesisimizde CNC torna, kaynak ve yüzey işleme hizmetleri sunuyoruz.",
      category_ids: ["sub-metal-cnc", "sub-metal-sheet"],
      logo_url: null,
      website: "https://marmara-metal.com",
      tax_number: "9876543210",
      address: "Tuzla Organize Sanayi, İstanbul",
      city: "İstanbul",
      phone: "+90 216 000 00 00",
      email: "demo@uretici.com",
      verified: true,
      slug: "marmara-metal",
      tagline: "Metal işlemede 20 yıllık uzmanlık",
      cover_image_url: "https://images.unsplash.com/photo-1565793298595-6a879b1d9492?w=1200&h=400&fit=crop",
      founded_year: 2004,
      employee_count: "50-100",
      profile_public: true,
      membership_plan: "pro",
      created_at: new Date().toISOString(),
    },
  },
  {
    id: DEMO_ADMIN_USER.id,
    email: DEMO_ADMIN_USER.email,
    password: DEMO_ADMIN_USER.password,
    full_name: "Admin Kullanıcı",
    role: "admin",
    company: {
      id: "admin-company-001",
      owner_id: DEMO_ADMIN_USER.id,
      name: "Platform Yönetimi",
      type: "demand_owner",
      status: "approved",
      description: "Platform yönetim hesabı",
      logo_url: null,
      website: null,
      tax_number: null,
      address: null,
      city: "İstanbul",
      phone: null,
      email: DEMO_ADMIN_USER.email,
      verified: true,
      created_at: new Date().toISOString(),
    },
  },
];

export const DEMO_CATEGORIES: Category[] = [
  { id: "main-metal", name: "Metal & Çelik", slug: "metal-celik", icon: null, parent_id: null },
  { id: "main-plastic", name: "Plastik & Polimer", slug: "plastik-polimer", icon: null, parent_id: null },
  { id: "main-textile", name: "Tekstil", slug: "tekstil", icon: null, parent_id: null },
  { id: "main-electronics", name: "Elektronik", slug: "elektronik", icon: null, parent_id: null },
  { id: "main-food", name: "Gıda", slug: "gida", icon: null, parent_id: null },
  { id: "main-furniture", name: "Mobilya & Ahşap", slug: "mobilya-ahsap", icon: null, parent_id: null },
  { id: "main-packaging", name: "Ambalaj", slug: "ambalaj", icon: null, parent_id: null },
  { id: "main-other", name: "Diğer", slug: "diger", icon: null, parent_id: null },
  { id: "main-construction-rough", name: "Kaba İnşaat Malzemeleri", slug: "kaba-insaat-malzemeleri", icon: null, parent_id: null },
  { id: "main-construction-finish", name: "İnce İnşaat ve Dekorasyon", slug: "ince-insaat-dekorasyon", icon: null, parent_id: null },
  { id: "main-construction-mep", name: "Mekanik ve Elektrik", slug: "mekanik-elektrik", icon: null, parent_id: null },
  { id: "main-construction-exterior", name: "Dış Cephe ve Peyzaj", slug: "dis-cephe-peyzaj", icon: null, parent_id: null },
  { id: "main-construction-services", name: "Hizmet ve Ekipman Tedariki", slug: "hizmet-ekipman-tedariki", icon: null, parent_id: null },
  { id: "main-hospital-medical", name: "Medikal ve Klinik Ekipman Entegrasyonu", slug: "medikal-klinik-ekipman", icon: null, parent_id: null },
  { id: "main-hospital-hygiene", name: "Özel Hijyen ve Yapısal Malzemeler", slug: "ozel-hijyen-yapisal-malzemeler", icon: null, parent_id: null },
  { id: "main-hospital-electrical", name: "Elektrik ve Zayıf Akım Sistemleri", slug: "elektrik-zayif-akim", icon: null, parent_id: null },
  { id: "main-hospital-support", name: "Teknik ve Destek Hizmetleri", slug: "teknik-destek-hizmetleri", icon: null, parent_id: null },
  { id: "main-industrial-structure", name: "Yapısal Çelik ve Prefabrik Sistemler", slug: "yapisal-celik-prefabrik", icon: null, parent_id: null },
  { id: "main-industrial-flooring", name: "Endüstriyel Zemin ve Altyapı", slug: "endustriyel-zemin-altyapi", icon: null, parent_id: null },
  { id: "main-industrial-mep", name: "Mekanik ve Endüstriyel Tesisat", slug: "mekanik-endustriyel-tesisat", icon: null, parent_id: null },
  { id: "main-industrial-logistics", name: "Lojistik ve İdari Tamamlayıcılar", slug: "lojistik-idari-tamamlayicilar", icon: null, parent_id: null },
  { id: "main-foodfacility-surface", name: "Hijyenik Yüzey ve Mimari Sistemler", slug: "hijyenik-yuzey-mimari", icon: null, parent_id: null },
  { id: "main-foodfacility-coldchain", name: "Soğuk Zincir ve İklimlendirme", slug: "soguk-zincir-iklimlendirme", icon: null, parent_id: null },
  { id: "main-foodfacility-plumbing", name: "Tesisat ve Arıtma Sistemleri", slug: "tesisat-aritma-sistemleri", icon: null, parent_id: null },
  { id: "main-foodfacility-safety", name: "Gıda Güvenliği ve Operasyonel Donanımlar", slug: "gida-guvenligi-operasyonel", icon: null, parent_id: null },
  { id: "main-support-marketing", name: "Reklam ve Pazarlama Ajansları", slug: "reklam-pazarlama-ajanslari", icon: null, parent_id: null },
  { id: "main-support-fleet", name: "Rent a Car ve Filo Kiralama", slug: "rent-a-car-filo-kiralama", icon: null, parent_id: null },
  { id: "main-project-datacenter", name: "Veri Merkezleri (Data Center)", slug: "veri-merkezleri", icon: null, parent_id: null },
  { id: "main-project-education", name: "Eğitim Yapıları (Okullar/Üniversiteler)", slug: "egitim-yapilari", icon: null, parent_id: null },
  { id: "main-project-tourism", name: "Turizm ve Otelcilik", slug: "turizm-otelcilik", icon: null, parent_id: null },
  { id: "main-project-infrastructure", name: "Altyapı Projeleri (Yol, Köprü, Tünel)", slug: "altyapi-projeleri", icon: null, parent_id: null },
  { id: "sub-metal-cnc", name: "CNC İşleme", slug: "cnc-isleme", icon: null, parent_id: "main-metal" },
  { id: "sub-metal-weld", name: "Kaynak & Montaj", slug: "kaynak-montaj", icon: null, parent_id: "main-metal" },
  { id: "sub-metal-sheet", name: "Sac Metal İşleme", slug: "sac-metal", icon: null, parent_id: "main-metal" },
  { id: "sub-plastic-injection", name: "Enjeksiyon Kalıp", slug: "enjeksiyon-kalip", icon: null, parent_id: "main-plastic" },
  { id: "sub-plastic-extrusion", name: "Ekstrüzyon", slug: "ekstruzyon", icon: null, parent_id: "main-plastic" },
  { id: "sub-textile-knit", name: "Örme & Dokuma", slug: "orme-dokuma", icon: null, parent_id: "main-textile" },
  { id: "sub-textile-dye", name: "Boya & Apre", slug: "boya-apre", icon: null, parent_id: "main-textile" },
  { id: "sub-electronics-pcb", name: "PCB Montaj", slug: "pcb-montaj", icon: null, parent_id: "main-electronics" },
  { id: "sub-electronics-cable", name: "Kablo & Harness", slug: "kablo-harness", icon: null, parent_id: "main-electronics" },
  { id: "sub-food-process", name: "Gıda İşleme", slug: "gida-isleme", icon: null, parent_id: "main-food" },
  { id: "sub-food-pack", name: "Gıda Ambalaj", slug: "gida-ambalaj", icon: null, parent_id: "main-food" },
  { id: "sub-furniture-cabinet", name: "Mobilya Üretimi", slug: "mobilya-uretimi", icon: null, parent_id: "main-furniture" },
  { id: "sub-furniture-wood", name: "Ahşap İşleme", slug: "ahsap-isleme", icon: null, parent_id: "main-furniture" },
  { id: "sub-pack-flex", name: "Esnek Ambalaj", slug: "esnek-ambalaj", icon: null, parent_id: "main-packaging" },
  { id: "sub-pack-rigid", name: "Sert Ambalaj", slug: "sert-ambalaj", icon: null, parent_id: "main-packaging" },
  { id: "sub-other-general", name: "Genel Üretim", slug: "genel-uretim", icon: null, parent_id: "main-other" },
  { id: "sub-construction-concrete", name: "Hazır Beton", slug: "hazir-beton", icon: null, parent_id: "main-construction-rough" },
  { id: "sub-construction-steel", name: "Demir ve Çelik", slug: "demir-celik", icon: null, parent_id: "main-construction-rough" },
  { id: "sub-construction-aggregate", name: "Agrega ve Hafriyat", slug: "agrega-hafriyat", icon: null, parent_id: "main-construction-rough" },
  { id: "sub-construction-brick", name: "Tuğla ve Gazbeton", slug: "tugla-gazbeton", icon: null, parent_id: "main-construction-rough" },
  { id: "sub-construction-ceramic", name: "Seramik ve Fayans", slug: "seramik-fayans", icon: null, parent_id: "main-construction-finish" },
  { id: "sub-construction-flooring", name: "Parke ve Ahşap Ürünleri", slug: "parke-ahsap-urunleri", icon: null, parent_id: "main-construction-finish" },
  { id: "sub-construction-paint", name: "Boya ve Yalıtım", slug: "boya-yalitim", icon: null, parent_id: "main-construction-finish" },
  { id: "sub-construction-drywall", name: "Alçı ve Asma Tavan", slug: "alci-asma-tavan", icon: null, parent_id: "main-construction-finish" },
  { id: "sub-construction-mechanical", name: "Mekanik Tesisat", slug: "mekanik-tesisat", icon: null, parent_id: "main-construction-mep" },
  { id: "sub-construction-electrical", name: "Elektrik Tesisat", slug: "elektrik-tesisat", icon: null, parent_id: "main-construction-mep" },
  { id: "sub-construction-smart-home", name: "Akıllı Ev Sistemleri", slug: "akilli-ev-sistemleri", icon: null, parent_id: "main-construction-mep" },
  { id: "sub-construction-facade", name: "Cephe Sistemleri", slug: "cephe-sistemleri", icon: null, parent_id: "main-construction-exterior" },
  { id: "sub-construction-landscape", name: "Peyzaj", slug: "peyzaj", icon: null, parent_id: "main-construction-exterior" },
  { id: "sub-construction-machinery", name: "İş Makineleri ve Ekipman", slug: "is-makineleri-ekipman", icon: null, parent_id: "main-construction-services" },
  { id: "sub-construction-isg", name: "İSG (İş Sağlığı ve Güvenliği)", slug: "isg", icon: null, parent_id: "main-construction-services" },
  { id: "sub-hospital-medical-gas", name: "Medikal Gaz Sistemleri", slug: "medikal-gaz-sistemleri", icon: null, parent_id: "main-hospital-medical" },
  { id: "sub-hospital-or-sterile", name: "Ameliyathane ve Sterilizasyon Ekipmanları", slug: "ameliyathane-sterilizasyon", icon: null, parent_id: "main-hospital-medical" },
  { id: "sub-hospital-radiology", name: "Radyoloji ve Görüntüleme", slug: "radyoloji-goruntuleme", icon: null, parent_id: "main-hospital-medical" },
  { id: "sub-hospital-medical-furniture", name: "Medikal Mobilya", slug: "medikal-mobilya", icon: null, parent_id: "main-hospital-medical" },
  { id: "sub-hospital-hygiene-flooring", name: "Hijyenik Zemin ve Duvar Kaplamaları", slug: "hijyenik-zemin-duvar", icon: null, parent_id: "main-hospital-hygiene" },
  { id: "sub-hospital-hygiene-doors", name: "Hastane Tipi Kapı Sistemleri", slug: "hastane-tipi-kapi", icon: null, parent_id: "main-hospital-hygiene" },
  { id: "sub-hospital-hvac", name: "Havalandırma (HVAC) ve Filtrasyon", slug: "havalandirma-hvac-filtrasyon", icon: null, parent_id: "main-hospital-hygiene" },
  { id: "sub-hospital-ups", name: "Kesintisiz Güç Kaynakları", slug: "kesintisiz-guc-kaynaklari", icon: null, parent_id: "main-hospital-electrical" },
  { id: "sub-hospital-nurse-call", name: "Hemşire Çağrı Sistemleri", slug: "hemsire-cagri-sistemleri", icon: null, parent_id: "main-hospital-electrical" },
  { id: "sub-hospital-bms", name: "Bina Yönetim Sistemleri (BMS)", slug: "bina-yonetim-sistemleri", icon: null, parent_id: "main-hospital-electrical" },
  { id: "sub-hospital-fire", name: "Yangın Algılama ve Söndürme", slug: "yangin-algilama-sondurme", icon: null, parent_id: "main-hospital-support" },
  { id: "sub-hospital-access", name: "Güvenlik ve Kartlı Geçiş", slug: "guvenlik-kartli-gecis", icon: null, parent_id: "main-hospital-support" },
  { id: "sub-industrial-steel", name: "Çelik Konstrüksiyon", slug: "celik-konstruksiyon", icon: null, parent_id: "main-industrial-structure" },
  { id: "sub-industrial-precast", name: "Prefabrik Betonarme", slug: "prefabrik-betonarme", icon: null, parent_id: "main-industrial-structure" },
  { id: "sub-industrial-sandwich", name: "Sandviç Paneller", slug: "sandvic-paneller", icon: null, parent_id: "main-industrial-structure" },
  { id: "sub-industrial-flooring", name: "Endüstriyel Zemin Kaplamaları", slug: "endustriyel-zemin-kaplamalari", icon: null, parent_id: "main-industrial-flooring" },
  { id: "sub-industrial-drainage", name: "Altyapı ve Drenaj", slug: "altyapi-drenaj", icon: null, parent_id: "main-industrial-flooring" },
  { id: "sub-industrial-energy", name: "Enerji Altyapısı", slug: "enerji-altyapisi", icon: null, parent_id: "main-industrial-flooring" },
  { id: "sub-industrial-process", name: "Proses Tesisatı", slug: "proses-tesisati", icon: null, parent_id: "main-industrial-mep" },
  { id: "sub-industrial-ventilation", name: "Havalandırma ve Toz Toplama", slug: "havalandirma-toz-toplama", icon: null, parent_id: "main-industrial-mep" },
  { id: "sub-industrial-fire", name: "Yangın Söndürme Sistemleri", slug: "yangin-sondurme-sistemleri", icon: null, parent_id: "main-industrial-mep" },
  { id: "sub-industrial-doors", name: "Endüstriyel Kapılar", slug: "endustriyel-kapilar", icon: null, parent_id: "main-industrial-logistics" },
  { id: "sub-industrial-partitions", name: "İdari Ofis Bölmeleri", slug: "idari-ofis-bolme", icon: null, parent_id: "main-industrial-logistics" },
  { id: "sub-industrial-security", name: "Güvenlik Sistemleri", slug: "guvenlik-sistemleri", icon: null, parent_id: "main-industrial-logistics" },
  { id: "sub-foodfacility-panels", name: "Panel Sistemleri", slug: "panel-sistemleri", icon: null, parent_id: "main-foodfacility-surface" },
  { id: "sub-foodfacility-flooring", name: "Zemin Sistemleri", slug: "zemin-sistemleri", icon: null, parent_id: "main-foodfacility-surface" },
  { id: "sub-foodfacility-stainless", name: "Paslanmaz Çelik Donanımlar", slug: "paslanmaz-celik-donanimlar", icon: null, parent_id: "main-foodfacility-surface" },
  { id: "sub-foodfacility-coldstorage", name: "Soğuk Hava Depoları", slug: "soguk-hava-depolari", icon: null, parent_id: "main-foodfacility-coldchain" },
  { id: "sub-foodfacility-ventilation", name: "Endüstriyel Havalandırma", slug: "endustriyel-havalandirma", icon: null, parent_id: "main-foodfacility-coldchain" },
  { id: "sub-foodfacility-climate", name: "Nem ve Isı Kontrol Sistemleri", slug: "nem-isi-kontrol", icon: null, parent_id: "main-foodfacility-coldchain" },
  { id: "sub-foodfacility-wastewater", name: "Endüstriyel Atık Su Arıtma", slug: "endustriyel-atik-su-aritma", icon: null, parent_id: "main-foodfacility-plumbing" },
  { id: "sub-foodfacility-piping", name: "Hijyenik Borulama", slug: "hijyenik-borulama", icon: null, parent_id: "main-foodfacility-plumbing" },
  { id: "sub-foodfacility-cip", name: "CIP (Cleaning In Place) Altyapısı", slug: "cip-altyapisi", icon: null, parent_id: "main-foodfacility-plumbing" },
  { id: "sub-foodfacility-hygiene-stations", name: "Hijyen İstasyonları", slug: "hijyen-istasyonlari", icon: null, parent_id: "main-foodfacility-safety" },
  { id: "sub-foodfacility-doors", name: "Hızlı Geçişli Kapılar", slug: "hizli-gecisli-kapilar", icon: null, parent_id: "main-foodfacility-safety" },
  { id: "sub-foodfacility-pest", name: "Zararlı Kontrolü", slug: "zararli-kontrolu", icon: null, parent_id: "main-foodfacility-safety" },
  { id: "sub-support-digital-marketing", name: "Dijital Pazarlama", slug: "dijital-pazarlama", icon: null, parent_id: "main-support-marketing" },
  { id: "sub-support-3d-render", name: "3D Görselleştirme ve Render", slug: "3d-gorsellestirme-render", icon: null, parent_id: "main-support-marketing" },
  { id: "sub-support-corporate-id", name: "Kurumsal Kimlik ve Basılı Medya", slug: "kurumsal-kimlik-basili-medya", icon: null, parent_id: "main-support-marketing" },
  { id: "sub-support-events", name: "Etkinlik Yönetimi", slug: "etkinlik-yonetimi", icon: null, parent_id: "main-support-marketing" },
  { id: "sub-support-passenger-fleet", name: "Binek Araç Filosu", slug: "binek-arac-filosu", icon: null, parent_id: "main-support-fleet" },
  { id: "sub-support-commercial-rental", name: "Ticari Araç ve Kamyonet Kiralama", slug: "ticari-arac-kamyonet-kiralama", icon: null, parent_id: "main-support-fleet" },
  { id: "sub-support-longterm-fleet", name: "Uzun Dönem Filo Kiralama", slug: "uzun-donem-filo-kiralama", icon: null, parent_id: "main-support-fleet" },
  { id: "sub-support-special-vehicles", name: "Özel Araç İhtiyaçları", slug: "ozel-arac-ihtiyaclari", icon: null, parent_id: "main-support-fleet" },
  { id: "sub-project-dc-electrical", name: "Elektrik Altyapısı", slug: "veri-merkezi-elektrik", icon: null, parent_id: "main-project-datacenter" },
  { id: "sub-project-dc-hvac", name: "Hassas İklimlendirme", slug: "hassas-iklimlendirme", icon: null, parent_id: "main-project-datacenter" },
  { id: "sub-project-dc-fire", name: "Yangın Söndürme", slug: "veri-merkezi-yangin-sondurme", icon: null, parent_id: "main-project-datacenter" },
  { id: "sub-project-dc-flooring", name: "Yükseltilmiş Döşemeler", slug: "yukseltilmis-dosemeler", icon: null, parent_id: "main-project-datacenter" },
  { id: "sub-project-dc-security", name: "Güvenlik Sistemleri", slug: "veri-merkezi-guvenlik", icon: null, parent_id: "main-project-datacenter" },
  { id: "sub-project-edu-acoustic", name: "Akustik Çözümler", slug: "akustik-cozumler", icon: null, parent_id: "main-project-education" },
  { id: "sub-project-edu-conference", name: "Konferans ve Sosyal Alan Ekipmanları", slug: "konferans-sosyal-alan", icon: null, parent_id: "main-project-education" },
  { id: "sub-project-edu-structure", name: "Yapısal Sistemler", slug: "egitim-yapisal-sistemler", icon: null, parent_id: "main-project-education" },
  { id: "sub-project-edu-accessibility", name: "Erişilebilirlik Donanımları", slug: "erisilebilirlik-donanimlari", icon: null, parent_id: "main-project-education" },
  { id: "sub-project-tour-interior", name: "İç Mekan ve Dekorasyon", slug: "ic-mekan-dekorasyon", icon: null, parent_id: "main-project-tourism" },
  { id: "sub-project-tour-automation", name: "Otomasyon Sistemleri", slug: "otel-otomasyon-sistemleri", icon: null, parent_id: "main-project-tourism" },
  { id: "sub-project-tour-bathroom", name: "Vitrifiye ve Banyo", slug: "vitrifiye-banyo", icon: null, parent_id: "main-project-tourism" },
  { id: "sub-project-tour-kitchen", name: "Profesyonel Mutfak ve Çamaşırhane", slug: "profesyonel-mutfak-camasirhane", icon: null, parent_id: "main-project-tourism" },
  { id: "sub-project-infra-materials", name: "Yapı Malzemeleri", slug: "altyapi-yapi-malzemeleri", icon: null, parent_id: "main-project-infrastructure" },
  { id: "sub-project-infra-geotextile", name: "Geotekstil Malzemeler", slug: "geotekstil-malzemeler", icon: null, parent_id: "main-project-infrastructure" },
  { id: "sub-project-infra-traffic", name: "Güvenlik ve Trafik", slug: "guvenlik-trafik", icon: null, parent_id: "main-project-infrastructure" },
  { id: "sub-project-infra-lighting", name: "Aydınlatma ve Drenaj", slug: "aydinlatma-drenaj", icon: null, parent_id: "main-project-infrastructure" },
];

export const DEMO_LISTINGS_SEED: Listing[] = [
  {
    id: "listing-demo-001",
    company_id: "demo-company-001",
    category_id: "sub-metal-sheet",
    title: "Paslanmaz Çelik Boru Üretimi",
    description: "Endüstriyel tesis için 500 adet paslanmaz çelik boru üretimi talep edilmektedir.",
    technical_details: "AISI 304, çap 50mm, et kalınlığı 2mm",
    budget_min: 50000,
    budget_max: 150000,
    delivery_time: "30 gün",
    city: "İstanbul",
    application_deadline: "2026-08-01",
    status: "active",
    view_count: 12,
    created_at: new Date().toISOString(),
    category: DEMO_CATEGORIES.find((c) => c.id === "sub-metal-sheet"),
  },
  {
    id: "listing-demo-002",
    company_id: "demo-company-001",
    category_id: "sub-plastic-injection",
    title: "Plastik Enjeksiyon Kalıp Üretimi",
    description: "Elektronik kutu için plastik enjeksiyon kalıbı üretimi talep edilmektedir.",
    technical_details: "ABS malzeme, 200x150x80mm",
    budget_min: 25000,
    budget_max: 80000,
    delivery_time: "45 gün",
    city: "Bursa",
    application_deadline: "2026-09-01",
    status: "active",
    view_count: 8,
    created_at: new Date().toISOString(),
    category: DEMO_CATEGORIES.find((c) => c.id === "sub-plastic-injection"),
  },
];
