import type { Message, NewsArticle, Notification, PortfolioItem } from "@/types";
import { DEMO_CATEGORIES, DEMO_LISTINGS_SEED, DEMO_USERS } from "./config";
import type { DemoApplication, DemoCatalog, DemoChatRoom, DemoSettings, DemoStore } from "./types";

const demandUser = DEMO_USERS[0];
const producerFreeUser = DEMO_USERS[1];
const producerUser = DEMO_USERS[2];

const now = new Date();
const hoursAgo = (h: number) => new Date(now.getTime() - h * 3600000).toISOString();

export const DEMO_APPLICATIONS_SEED: DemoApplication[] = [
  {
    id: "app-free-001",
    listing_id: "listing-demo-002",
    producer_company_id: producerFreeUser.company.id,
    applicant_id: producerFreeUser.id,
    cover_letter:
      "Plastik enjeksiyon kalıbı konusunda 8 yıllık deneyimimiz var. Numune ve teknik çizim paylaşımına hazırız.",
    proposed_budget: 62000,
    proposed_delivery: "40 gün",
    status: "pending",
    created_at: hoursAgo(12),
    listing_title: "Plastik Enjeksiyon Kalıp Üretimi",
    producer_name: producerFreeUser.company.name,
    producer_city: producerFreeUser.company.city!,
  },
  {
    id: "app-001",
    listing_id: "listing-demo-001",
    producer_company_id: "producer-001",
    applicant_id: "producer-user-001",
    cover_letter:
      "25 yıllık metal işleme tecrübemizle paslanmaz çelik boru üretiminde uzmanız. ISO 9001 sertifikalı tesisimizde talebinizi karşılayabiliriz.",
    proposed_budget: 95000,
    proposed_delivery: "25 gün",
    status: "pending",
    created_at: hoursAgo(5),
    listing_title: "Paslanmaz Çelik Boru Üretimi",
    producer_name: "Anadolu Metal San.",
    producer_city: "Bursa",
  },
  {
    id: "app-003",
    listing_id: "listing-demo-001",
    producer_company_id: producerUser.company.id,
    applicant_id: producerUser.id,
    cover_letter:
      "Metal ve çelik işleme alanında deneyimli ekibimizle projenizi zamanında teslim edebiliriz.",
    proposed_budget: 88000,
    proposed_delivery: "22 gün",
    status: "approved",
    created_at: hoursAgo(48),
    listing_title: "Paslanmaz Çelik Boru Üretimi",
    producer_name: producerUser.company.name,
    producer_city: producerUser.company.city!,
  },
];

export const DEMO_CHAT_ROOMS_SEED: DemoChatRoom[] = [
  {
    id: "room-001",
    application_id: "app-003",
    listing_id: "listing-demo-001",
    listing_title: "Paslanmaz Çelik Boru Üretimi",
    demand_company_id: demandUser.company.id,
    demand_company_name: demandUser.company.name,
    producer_company_id: producerUser.company.id,
    producer_name: producerUser.company.name,
    created_at: hoursAgo(36),
  },
];

export const DEMO_MESSAGES_SEED: Message[] = [
  {
    id: "msg-001",
    room_id: "room-001",
    sender_id: producerUser.id,
    type: "text",
    content: "Merhaba, başvurumuz onaylandığı için teşekkür ederiz. Detayları konuşmak isteriz.",
    file_url: null,
    file_name: null,
    offer_amount: null,
    is_read: true,
    created_at: hoursAgo(35),
  },
  {
    id: "msg-002",
    room_id: "room-001",
    sender_id: demandUser.id,
    type: "text",
    content: "Merhaba, teknik çizimleri paylaşabilir misiniz? Ayrıca teslim süresi 22 gün kesin mi?",
    file_url: null,
    file_name: null,
    offer_amount: null,
    is_read: true,
    created_at: hoursAgo(34),
  },
  {
    id: "msg-003",
    room_id: "room-001",
    sender_id: producerUser.id,
    type: "offer",
    content: "Güncellenmiş teklifimizi paylaşıyorum.",
    file_url: null,
    file_name: null,
    offer_amount: 85000,
    is_read: true,
    created_at: hoursAgo(2),
  },
  {
    id: "msg-004",
    room_id: "room-001",
    sender_id: demandUser.id,
    type: "text",
    content: "Teknik çizimleri ekte paylaştım, inceleyip dönüş yapar mısınız?",
    file_url: null,
    file_name: null,
    offer_amount: null,
    is_read: false,
    created_at: hoursAgo(1),
  },
];

export const DEMO_NOTIFICATIONS_SEED: Notification[] = [
  // Talep sahibi bildirimleri
  {
    id: "notif-001",
    user_id: demandUser.id,
    type: "company_approved",
    title: "Firmanız Onaylandı",
    message: "Demo Kurumsal A.Ş. hesabınız aktif edildi.",
    link: "/dashboard/ilanlar/yeni",
    is_read: true,
    created_at: hoursAgo(72),
  },
  {
    id: "notif-002",
    user_id: demandUser.id,
    type: "new_application",
    title: "Yeni Teklif",
    message: "Anadolu Metal San. ilanınıza başvurdu.",
    link: "/dashboard/basvurular",
    is_read: false,
    created_at: hoursAgo(5),
  },
  {
    id: "notif-003",
    user_id: demandUser.id,
    type: "new_application",
    title: "Yeni Teklif",
    message: "Marmara Metal San. ilanınıza başvurdu.",
    link: "/dashboard/basvurular",
    is_read: false,
    created_at: hoursAgo(3),
  },
  {
    id: "notif-004",
    user_id: demandUser.id,
    type: "new_message",
    title: "Yeni Mesaj",
    message: "Marmara Metal San. size yeni bir teklif gönderdi.",
    link: "/dashboard/mesajlar/room-001",
    is_read: false,
    created_at: hoursAgo(2),
  },
  // Üretici bildirimleri
  {
    id: "notif-p01",
    user_id: producerUser.id,
    type: "company_approved",
    title: "Firmanız Onaylandı",
    message: "Marmara Metal San. hesabınız aktif edildi. Kategori eşleşen ilanlara başvurabilirsiniz.",
    link: "/dashboard/ilanlar",
    is_read: true,
    created_at: hoursAgo(96),
  },
  {
    id: "notif-p02",
    user_id: producerUser.id,
    type: "application_approved",
    title: "Teklifiniz Onaylandı",
    message: "Paslanmaz Çelik Boru Üretimi ilanına verdiğiniz teklif onaylandı!",
    link: "/dashboard/mesajlar/room-001",
    is_read: true,
    created_at: hoursAgo(36),
  },
  {
    id: "notif-p03",
    user_id: producerUser.id,
    type: "new_message",
    title: "Yeni Mesaj",
    message: "Demo Kurumsal A.Ş. size mesaj gönderdi.",
    link: "/dashboard/mesajlar/room-001",
    is_read: false,
    created_at: hoursAgo(34),
  },
  {
    id: "notif-p04",
    user_id: producerUser.id,
    type: "new_listing_match",
    title: "Kategorinize Uygun Yeni İlan",
    message: '"Paslanmaz Çelik Boru Üretimi" ilanı üretim kategorilerinize uygun.',
    link: "/ilanlar/listing-demo-001",
    is_read: false,
    created_at: hoursAgo(1),
  },
  {
    id: "notif-p05",
    user_id: producerUser.id,
    type: "new_listing",
    title: "Yeni İlan",
    message: "Plastik Enjeksiyon Kalıp Üretimi ilanı yayınlandı.",
    link: "/ilanlar/listing-demo-002",
    is_read: false,
    created_at: hoursAgo(10),
  },
];

export const DEMO_PORTFOLIO_SEED: PortfolioItem[] = [
  {
    id: "port-001",
    company_id: producerUser.company.id,
    title: "Endüstriyel Paslanmaz Boru Hattı",
    description: "Gıda sektörü için 2.000 metre AISI 304 boru üretimi ve montajı.",
    image_url: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=600&h=400&fit=crop",
    year: 2025,
    client_name: "Gıda A.Ş.",
    created_at: hoursAgo(200),
  },
  {
    id: "port-002",
    company_id: producerUser.company.id,
    title: "CNC Torna Parça Serisi",
    description: "Otomotiv yan sanayi için hassas toleranslı 5.000 adet parça üretimi.",
    image_url: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=600&h=400&fit=crop",
    year: 2024,
    client_name: "Otomotiv Ltd.",
    created_at: hoursAgo(400),
  },
  {
    id: "port-003",
    company_id: producerUser.company.id,
    title: "Çelik Konstrüksiyon Projesi",
    description: "Fabrika binası için 120 ton çelik konstrüksiyon imalat ve montaj.",
    image_url: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=600&h=400&fit=crop",
    year: 2023,
    client_name: "İnşaat Grubu",
    created_at: hoursAgo(600),
  },
  {
    id: "port-d01",
    company_id: demandUser.company.id,
    title: "Otomotiv Tedarik Zinciri",
    description: "3 farklı üretici ile 18 aylık metal parça tedarik projesi yönetimi.",
    image_url: "https://images.unsplash.com/photo-1565793298595-6a879b1d9492?w=600&h=400&fit=crop",
    year: 2025,
    client_name: "İç Proje",
    created_at: hoursAgo(150),
  },
  {
    id: "port-d02",
    company_id: demandUser.company.id,
    title: "Tekstil Hammadde Tedariki",
    description: "Yıllık 80.000 metre kumaş tedarik anlaşması koordinasyonu.",
    image_url: "https://images.unsplash.com/photo-1523381210434-95eabe85d79e?w=600&h=400&fit=crop",
    year: 2024,
    client_name: "İç Proje",
    created_at: hoursAgo(350),
  },
];

export const DEMO_NEWS_SEED: NewsArticle[] = [
  {
    id: "news-001",
    title: "B2B Platformu Resmi Olarak Yayında",
    slug: "b2b-platformu-yayinda",
    summary: "Türkiye'nin yeni nesil üretim ve tedarik platformu hizmete girdi.",
    content:
      "B2B Üretim ve Tedarik Platformu, kurumsal firmalar ile doğrulanmış üreticileri tek çatı altında buluşturuyor. Platform üzerinden ilan yayınlayabilir, teklif alabilir ve güvenli mesajlaşma ile süreçlerinizi yönetebilirsiniz.\n\nDemo modunda tüm özellikleri ücretsiz deneyebilirsiniz.",
    cover_image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=1200&h=600&fit=crop",
    published_at: "2026-06-01T10:00:00Z",
    created_at: "2026-06-01T10:00:00Z",
    is_published: true,
    author_name: "Platform Ekibi",
  },
  {
    id: "news-002",
    title: "Tedarikçi Firmalar İçin Yeni Özellikler",
    slug: "uretici-yeni-ozellikler",
    summary: "Pro üyelik, profil sayfası ve gelişmiş raporlar eklendi.",
    content:
      "Tedarikçi firmalar artık Pro üyelikle herkese açık profil sayfası oluşturabilir, önceki işlerini paylaşabilir ve gelişmiş raporlara erişebilir.\n\nÜcretsiz planda aylık 10 ilana teklif verme imkânı sunulmaya devam ediyor.",
    cover_image: "https://images.unsplash.com/photo-1565793298595-6a879b1d9492?w=1200&h=600&fit=crop",
    published_at: "2026-05-25T14:00:00Z",
    created_at: "2026-05-25T14:00:00Z",
    is_published: true,
    author_name: "Platform Ekibi",
  },
  {
    id: "news-003",
    title: "Sektör Raporu: 2026 Üretim Trendleri",
    slug: "sektor-raporu-2026",
    summary: "Türkiye'de üretim sektörünün 2026 yılı beklentileri ve trendleri.",
    content:
      "2026 yılında Türkiye üretim sektöründe dijitalleşme, yerel tedarik zinciri güçlendirme ve sürdürülebilir üretim öne çıkıyor.\n\nB2B platformları aracılığıyla tedarik süreçlerini dijitalleştiren firmalar, operasyonel verimlilikte belirgin artış kaydediyor.",
    cover_image: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=1200&h=600&fit=crop",
    published_at: "2026-05-20T09:00:00Z",
    created_at: "2026-05-20T09:00:00Z",
    is_published: true,
    author_name: "Araştırma Ekibi",
  },
];

export const DEMO_CATALOGS_SEED: DemoCatalog[] = [
  {
    id: "catlog-001",
    company_id: producerUser.company.id,
    title: "2026 Ürün Kataloğu",
    description: "Metal ve tekstil yan sanayi ürün gamı",
    file_name: "marmara-tekstil-katalog-2026.pdf",
    created_at: hoursAgo(120),
  },
  {
    id: "catlog-002",
    company_id: producerUser.company.id,
    title: "Sertifikalar ve Referanslar",
    description: "ISO 9001, CE belgeleri ve referans projeler",
    file_name: "marmara-sertifikalar.pdf",
    created_at: hoursAgo(80),
  },
];

export const DEFAULT_DEMO_SETTINGS: DemoSettings = {
  email_notifications: true,
  sms_notifications: false,
  application_alerts: true,
  message_alerts: true,
  language: "tr",
};

export function createInitialDemoStore(): DemoStore {
  return {
    registeredUsers: [],
    listings: [...DEMO_LISTINGS_SEED],
    applications: [...DEMO_APPLICATIONS_SEED],
    chatRooms: [...DEMO_CHAT_ROOMS_SEED],
    messages: [...DEMO_MESSAGES_SEED],
    notifications: [...DEMO_NOTIFICATIONS_SEED],
    companies: {
      [demandUser.company.id]: { ...demandUser.company },
      [producerFreeUser.company.id]: { ...producerFreeUser.company },
      [producerUser.company.id]: { ...producerUser.company },
      "producer-001": {
        id: "producer-001",
        owner_id: "producer-user-001",
        name: "Anadolu Metal San.",
        type: "producer",
        status: "approved",
        description: "Çelik ve metal işleme uzmanı. Bursa'da 15.000 m² üretim tesisi.",
        logo_url: null,
        website: "https://anadolu-metal.com",
        tax_number: null,
        address: null,
        city: "Bursa",
        phone: "+90 224 000 00 00",
        email: null,
        verified: true,
        category_ids: ["sub-metal-cnc"],
        slug: "anadolu-metal",
        tagline: "Bursa'nın çelik işleme merkezi",
        cover_image_url: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=1200&h=400&fit=crop",
        founded_year: 1998,
        employee_count: "100-250",
        profile_public: false,
        membership_plan: "free",
        created_at: new Date().toISOString(),
      },
      "admin-company-001": {
        id: "admin-company-001",
        owner_id: "demo-admin-001",
        name: "Platform Yönetimi",
        type: "demand_owner",
        status: "approved",
        description: "Platform yönetim hesabı",
        logo_url: null,
        website: null,
        tax_number: null,
        address: null,
        city: "İstanbul",
        phone: null,
        email: "demo@admin.com",
        verified: true,
        created_at: new Date().toISOString(),
      },
      "producer-pending-001": {
        id: "producer-pending-001",
        owner_id: "producer-pending-user",
        name: "Vizyon Makine Ltd.",
        type: "producer",
        status: "pending",
        description: "CNC işleme ve hassas torna üretimi. Onay bekliyor.",
        logo_url: null,
        website: null,
        tax_number: null,
        address: "Gebze OSB, Kocaeli",
        city: "Kocaeli",
        phone: "+90 262 000 00 00",
        email: "basvuru@vizyon-makine.com",
        verified: false,
        category_ids: ["sub-metal-cnc"],
        slug: null,
        tagline: "Hassas metal işleme",
        profile_public: false,
        membership_plan: "free",
        created_at: new Date().toISOString(),
      },
      "producer-002": {
        id: "producer-002",
        owner_id: "producer-user-002",
        name: "Ege Plastik A.Ş.",
        type: "producer",
        status: "approved",
        description: "Plastik enjeksiyon ve kalıp üretiminde uzman firma.",
        logo_url: null,
        website: null,
        tax_number: null,
        address: null,
        city: "İzmir",
        phone: null,
        email: null,
        verified: true,
        category_ids: ["sub-plastic-injection"],
        slug: "ege-plastik",
        tagline: "Plastik enjeksiyon çözümleri",
        profile_public: false,
        membership_plan: "free",
        created_at: new Date().toISOString(),
      },
      "demand-ref-001": {
        id: "demand-ref-001",
        owner_id: "demand-ref-001",
        name: "Modül Mobilya A.Ş.",
        type: "demand_owner",
        status: "approved",
        description: "Ofis ve konut mobilyası tedarikinde Türkiye genelinde üretici ağı yönetiyoruz.",
        logo_url: null,
        website: "https://modul-mobilya.com",
        tax_number: null,
        address: "Ostim, Ankara",
        city: "Ankara",
        phone: "+90 312 000 00 00",
        email: null,
        verified: true,
        slug: "modul-mobilya",
        tagline: "Kurumsal mobilya tedariki",
        cover_image_url: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&h=400&fit=crop",
        founded_year: 2008,
        employee_count: "50-100",
        profile_public: true,
        membership_plan: "free",
        created_at: new Date().toISOString(),
      },
      "demand-ref-002": {
        id: "demand-ref-002",
        owner_id: "demand-ref-002",
        name: "Atlas Gıda San.",
        type: "demand_owner",
        status: "approved",
        description: "Gıda ve ambalaj tedarikinde güvenilir kurumsal müşteri.",
        logo_url: null,
        website: null,
        tax_number: null,
        address: null,
        city: "İzmir",
        phone: null,
        email: null,
        verified: true,
        slug: "atlas-gida",
        tagline: "Gıda sektöründe tedarik yönetimi",
        cover_image_url: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=1200&h=400&fit=crop",
        founded_year: 2015,
        employee_count: "100-250",
        profile_public: true,
        membership_plan: "free",
        created_at: new Date().toISOString(),
      },
      "producer-ref-001": {
        id: "producer-ref-001",
        owner_id: "producer-ref-001",
        name: "Vega Tekstil Üretim",
        type: "producer",
        status: "approved",
        description: "Konfeksiyon ve tekstil üretiminde 18 yıllık deneyim.",
        logo_url: null,
        website: null,
        tax_number: null,
        address: null,
        city: "Bursa",
        phone: null,
        email: null,
        verified: true,
        category_ids: ["sub-textile-knit"],
        slug: "vega-tekstil",
        tagline: "Tekstil üretiminde güvenilir çözüm ortağı",
        cover_image_url: "https://images.unsplash.com/photo-1586495777744-4416f2107adc?w=1200&h=400&fit=crop",
        founded_year: 2006,
        employee_count: "100-250",
        profile_public: true,
        membership_plan: "pro",
        created_at: new Date().toISOString(),
      },
      "producer-ref-002": {
        id: "producer-ref-002",
        owner_id: "producer-ref-002",
        name: "Delta Elektronik Montaj",
        type: "producer",
        status: "approved",
        description: "PCB montaj ve elektronik üretim hizmetleri.",
        logo_url: null,
        website: null,
        tax_number: null,
        address: null,
        city: "Kocaeli",
        phone: null,
        email: null,
        verified: true,
        category_ids: ["sub-electronics-pcb"],
        slug: "delta-elektronik",
        tagline: "Elektronik montaj ve üretim",
        cover_image_url: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200&h=400&fit=crop",
        founded_year: 2012,
        employee_count: "50-100",
        profile_public: true,
        membership_plan: "pro",
        created_at: new Date().toISOString(),
      },
      "producer-ref-003": {
        id: "producer-ref-003",
        owner_id: "producer-ref-003",
        name: "Ankara Makine Ltd.",
        type: "producer",
        status: "approved",
        description: "CNC işleme ve makine parçası üretimi.",
        logo_url: null,
        website: null,
        tax_number: null,
        address: null,
        city: "Ankara",
        phone: null,
        email: null,
        verified: true,
        category_ids: ["sub-metal-cnc"],
        slug: "ankara-makine",
        tagline: "Hassas metal işleme",
        cover_image_url: "https://images.unsplash.com/photo-1565043589221-1a6fd9ae45c7?w=1200&h=400&fit=crop",
        founded_year: 2001,
        employee_count: "50-100",
        profile_public: true,
        membership_plan: "pro",
        created_at: new Date().toISOString(),
      },
    },
    settings: {
      [demandUser.id]: { ...DEFAULT_DEMO_SETTINGS },
      [producerFreeUser.id]: { ...DEFAULT_DEMO_SETTINGS },
      [producerUser.id]: { ...DEFAULT_DEMO_SETTINGS },
    },
    catalogs: [...DEMO_CATALOGS_SEED],
    portfolio: [...DEMO_PORTFOLIO_SEED],
    news: [...DEMO_NEWS_SEED],
    categories: DEMO_CATEGORIES.map((c, i) => ({ ...c, sort_order: i, is_active: true })),
  };
}
